language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
  - "pip install -U pip"
  - "python setup.py install
install:
  - pip install -r requirements.txt
  - pip3 install holidays
# command to run tests
script:
  - pytest
 
